### ISSUE TITLE
Gift Cards Edit - Due Nov 1

### ISSUE THREAD

**Issue by madeleineworrall** [PrimitiveSocial/Orlandos#2]
Can we move up the Gift Card section on the Orlando site too? - see attachment from client
[gift card relocate (2).pdf](https://github.com/PrimitiveSocial/Orlandos/files/3779373/gift.card.relocate.2.pdf)

@jetercotton Mind finding a dev for this? 

Thanks!!!

**Comment by jetercotton** [comment]
@madeleineworrall Sounds good! @matthewPrimitive You're up my dude.

**Comment by madeleineworrall** [comment]
It's both of them! Caprock and Orlando's!
